### ISSUE TITLE
[CHECKLIST] Proposal Implementations and Testing 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#167]
# Overview
The goal of this checklist is to act as the single source of truth for Proposal related implementations, and testing.

### Related Issues

- [[CHECKLIST] E2E SignatureBridge Integration](https://github.com/webb-tools/dkg-substrate/issues/92)
- [[SPEC] Proposals and their pallet flow on Substrate](https://github.com/webb-tools/protocol-substrate/issues/142)
- [[SPEC] Proposals and their Contracts on EVM/Solidity](https://github.com/webb-tools/protocol-solidity/issues/83)

### Proposal Implementation Tracker
| DKG | EVM | SUB | ink!
|:-:|:-:|:-:|:-:|
| Refresh | N/A | N/A |  N/A
| AnchorCreate | N/A  | [execute_anchor_create_proposal](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/anchor-handler/src/lib.rs#L151) |  N/A
| AnchorUpdate | [updateEdge](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/anchors/LinkableTree.sol#L55) | [execute_anchor_update_proposal](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/anchor-handler/src/lib.rs#L167) | ❌ 
| TokenAdd | [add](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/tokens/GovernedTokenWrapper.sol#L42) | [execute_add_token_to_pool_share](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper-handler/src/lib.rs#L127) | ❌ 
| TokenRemove | [remove](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/tokens/GovernedTokenWrapper.sol#L56) | [execute_remove_token_from_pool_share](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper-handler/src/lib.rs#L141)  | ❌ 
| WrappingFeeUpdate | [setFee](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/tokens/GovernedTokenWrapper.sol#L82) | [execute_wrapping_fee_proposal](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper-handler/src/lib.rs#L113)  | ❌ 
| RescueToken | [rescueTokens](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/Treasury.sol#L25) | ❌  | ❌ 
| MaxDepositLimitUpdate, MinWithdrawalLimitUpdate | [configureLimits](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/vanchors/VAnchorBase.sol#L75) | ❌  | ❌ 
| ❌  | [setFeeRecipient](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/tokens/GovernedTokenWrapper.sol#L90) | ❌  | ❌ 
| ❌  | [treasurySetHandler](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/Treasury.sol#L53) | N/A  | ❌ 
| MaxExtLimitUpdate | ❌  | ❌  | ❌ 
| MaxFeeLimitUpdate | ❌  | ❌  | ❌ 
| ResourceIdUpdate | [adminSetResourceWithSignature](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/SignatureBridge.sol#L50) | ❌  | ❌ 

#### Unimplemented dkg-substrate

- [ ] [TASK] Implement **`TreasuryHandlerUpdate`** Proposal
- [ ] [TASK] Implement **`FeeRecipientUpdate`** Proposal

#### Unimplemented protocol-substrate

- [ ] [TASK] Implement **`RescueTokens`** Proposal
- [ ] [TASK] Implement **`ConfigLimits`** Proposal
- [ ] [TASK] Implement **`ResourceIDUpdate`** Proposal
- [ ] [TASK] Implement **`MaxExtLimitUpdate`** Proposal
- [ ] [TASK] Implement **`MaxFeeLimitUpdate`** Proposal
- [ ] [TASK] Implement **`FeeRecipientUpdate`** Proposal

#### Unimplemented protocol-solidity

- [ ] [TASK] Implement **`MaxExtLimitUpdate`** Proposal
- [ ] [TASK] Implement **`MaxFeeLimitUpdate`** Proposal

#### Unimplemented protocol-ink!

- [ ] [TASK] Implement **`anchor_update_proposal`**
- [ ] [TASK] Implement **`add_token_to_pool_share`**
- [ ] [TASK] Implement **`remove_token_to_pool_share`**
- [ ] [TASK] Implement **`wrapping_fee_proposal`**
- [ ] [TASK] Implement **`RescueTokens`** Proposal
- [ ] [TASK] Implement **`ConfigLimits`** Proposal
- [ ] [TASK] Implement **`ResourceIDUpdate`** Proposal
- [ ] [TASK] Implement **`MaxExtLimitUpdate`** Proposal
- [ ] [TASK] Implement **`MaxFeeLimitUpdate`** Proposal
- [ ] [TASK] Implement **`FeeRecipientUpdate`** Proposal

#### dkg-substrate proposals for Substrate
- [ ] [TASK] E2E Test anchor `create` and `update` call proposals to the DKG for Substrate.
- [ ] [TASK] E2E Test token (`add`, `remove`, `set fee`) call proposals to the DKG for Substrate.
- [ ] [TASK] E2E Test `setResourceID` proposal to the DKG for Substrate.
- [ ] [TASK] E2E Test `rescueToken` call proposals to the DKG for Substrate.
- [ ] [TASK] E2E Test `MaxDepositLimitUpdate` and `MinWithdrawalLimitUpdate` call proposals to the DKG for Substrate.
- [ ] [TASK] E2E Test `MaxExtLimitUpdate`, and `MaxFeeLimitUpdate` call proposals to the DKG for Substrate.

#### dkg-substrate proposals for EVM
- [ ] [TASK] E2E Test `setResourceID` proposal to the DKG for EVM.
- [ ] [TASK] E2E Test `rescueToken` call proposals to the DKG for EVM.
- [ ] [TASK] E2E Test  `MaxDepositLimitUpdate` and `MinWithdrawalLimitUpdate` call proposals to the DKG for EVM.
- [ ] [TASK] E2E Test `MaxExtLimitUpdate`, and `MaxFeeLimitUpdate` call proposals to the DKG for EVM.
