### ISSUE TITLE
[TASK] Add validation over EVM addresses

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#204]
**Task summary**

We should be validating EVM addresses within `dkg-runtime-primitives/src/handlers/evm`.

- [ ] Validate in `add_token_to_set.rs`
- [x] Ensure function sig is not zerio in `anchor_update.rs`
- [ ] Validate in `bytes32_update.rs`
- [ ] Validate in `fee_recipient_update.rs`
- [ ] Validate in `fee_update.rs`
- [ ] Validate in `remove_token_from_set.rs`
- [ ] Validate in `rescue_tokens.rs`
- [ ] Validate in `resource_id_update.rs`
- [ ] Validate in `set_treasury_handler.rs`
- [ ] Validate in `set_verifier.rs`

**Specification reference**

- 

**Other information and links**
