### ISSUE TITLE
[CHECKLIST] Dkg-substrate Documentation / Usability 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#205]
# Overview 

This checklist describes all the documentation related tasks that are required to be completed to make the dkg-substrate repo well documented. 

## Checklist 

- [ ] Add CONTRIBUTOR.md 
- [ ] Add accurate and ready chainspec.json files for standalone and parachain setup 
- [ ] Add license header check in CI
- [ ] Remove all unused, dead, code/imports - remove compiler warnings
- [ ] Add documentation check / tester to CI
- [ ] Clean up and update README.md

### `dkg-gadget` documentation
- [ ] Add and update license headers for all files in `dkg-gadget`
- [ ] Add inline documentation in `/messages/misbehaviour_report.rs`
- [ ] Add inline documentation in `/messages/public_key_gossip.rs`
- [ ] Improve inline documentation for dkg-gadget specific errors in `errors.rs`
- [ ] Update inline documentation in `worker.rs`

### `dkg-primitives` documentation
- [ ] Add and update license headers for all files in `dkg-primitives`
- [ ] Improve file documentation in `rounds/dkg.rs`
- [ ] Add inline documentation in `/rounds/keygen.rs`
- [ ] Add inline documentation in `/rounds/offline.rs`
- [ ] Add inline documentation in `/rounds/sign.rs`
- [ ] Add inline documentation in `keys.rs`
- [ ] Add inline documentation in `types.rs`
- [ ] Add inline documentation in `utils.rs`

### `dkg-runtime-primitives` documentation
- [ ] Add and update license headers for all files in `dkg-runtime-primitives`
- [ ] Improve inline documentation in `decode_proposal.rs`
- [ ] Improve inline documentation in `lib.rs`, including all public const
- [ ] Add inline documentation in `proposal.rs`
- [ ] Add documentation to public traits in `traits.rs`
- [ ] Add inline documentation to `utils.rs`

### `dkg-test-suite` documentation
- [ ] Add and update license headers for all files in `dkg-test-suite`
- [ ] Improve and add more verbosity to testing README.md 

### `dkg-metadata` pallet documentation
- [ ] Add and update license headers for all files in `dkg-metadata`
- [ ] Add pallet overview documentation at top of each file
- [ ] Add inline documentation to public functions that are not traits in `lib.rs`
- [ ] Add inline documentation to public functions that are not traits in `mock.rs`
- [ ] Add inline documentation in `types.rs`

### `dkg-proposal-handler` pallet documentation
- [ ] Update blank README.md file 
- [ ] Add and update license headers for all files in `dkg-proposal-handler`
- [ ] Add pallet overview documentation at top of each file
- [ ] Add documentation to each public trait definition
- [ ] Add inline documentation to public functions that are not traits

### `dkg-proposal` pallet documentation
- [ ] Add and update license headers for all files in `dkg-proposal`
- [ ] Add pallet overview documentation at top of each file
- [ ] Add documentation to each public trait definition
- [ ] Add inline documentation to public functions that are not traits
