### ISSUE TITLE
[TASK] dkg-gadget documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#206]
**Task summary**

- [ ] Add and update license headers for all files in `dkg-gadget`
- [ ] Add inline documentation in `/messages/misbehaviour_report.rs`
- [ ] Add inline documentation in `/messages/public_key_gossip.rs`
- [ ] Improve inline documentation for dkg-gadget specific errors in `errors.rs`
- [ ] Update inline documentation in `worker.rs`

**Other information and links**

See [Rust docs best practices](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) for proper formatting.
