### ISSUE TITLE
[TASK] `dkg-primitives` documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#207]
**Task summary**

- [ ] Add and update license headers for all files in `dkg-primitives`
- [ ] Improve file documentation in `rounds/dkg.rs`
- [ ] Add inline documentation in `/rounds/keygen.rs`
- [ ] Add inline documentation in `/rounds/offline.rs`
- [ ] Add inline documentation in `/rounds/sign.rs`
- [ ] Add inline documentation in `keys.rs`
- [ ] Add inline documentation in `types.rs`
- [ ] Add inline documentation in `utils.rs`

**Other information and links**

See [Rust docs best practices](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) for proper formatting.
