### ISSUE TITLE
[TASK] `dkg-runtime-primitives` documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#208]
**Task summary**

- [ ] Add and update license headers for all files in `dkg-runtime-primitives`
- [ ] Improve inline documentation in `decode_proposal.rs`
- [ ] Improve inline documentation in `lib.rs`, including all public const
- [ ] Add inline documentation in `proposal.rs`
- [ ] Add documentation to public traits in `traits.rs`
- [ ] Add inline documentation to `utils.rs`

**Other information and links**

See [Rust docs best practices](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) for proper formatting.
