### ISSUE TITLE
[TASK] `dkg-metadata` pallet documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#210]
**Task summary**

Ideally pallet documentation should follow similar format as [here](https://github.com/paritytech/substrate/blob/master/frame/atomic-swap/src/lib.rs#L18).

- [ ] Add and update license headers for all files in `dkg-metadata`
- [ ] Add pallet overview documentation at top of each file
- [ ] Add inline documentation to public functions that are not traits in `lib.rs`
- [ ] Add inline documentation to public functions that are not traits in `mock.rs`
- [ ] Add inline documentation in `types.rs`

**Other information and links**

See [Rust docs best practices](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) for proper formatting.
