### ISSUE TITLE
[TASK] `dkg-proposal` pallet documentation

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#212]
**Task summary**

Ideally pallet documentation should follow similar format as [here](https://github.com/paritytech/substrate/blob/master/frame/atomic-swap/src/lib.rs#L18).

- [x] Add README.md to describe pallet functionality
- [ ] Add and update license headers for all files in `dkg-proposal`
- [ ] Add pallet overview documentation at top of each file
- [ ] Add documentation to each public trait definition
- [ ] Add inline documentation to public functions that are not traits

**Other information and links**

See [Rust docs best practices](https://doc.rust-lang.org/rustdoc/how-to-write-documentation.html) for proper formatting.
