### ISSUE TITLE
[CHECKLIST] [WIP] Launch readiness phase-1 | DKG Alpha TestNet 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#229]
# Overview

The goal of this checklist is to outline all requirements to have an internal TestNet. It is likely we will experience stalls, discover bugs, and identify areas of improvement. This may also be used for other parts of the Webb ecosystem (e.g. Anchor protocol).

This is an essential step to ensure the DKG is launch-ready before joining the parachain testnet Rococo (phase-2).   

## Checklist

- [ ] [TASK] Deploy mixer and anchor  

### Feature-complete list
- [ ] [TASK] Run resets where chain nonce zeroes
- [ ] [TASK] Initiate and complete key-gen protocol 
           - [ ] Node are generating secret parameter 
           - [ ] Nodes are able to gossip VSS of each parties secret parameter
           - [ ] Each party can generate their private signing key share 
- [ ] [TASK] Proceed through rounds with adequate signers   
- [ ] [TASK] Handle inbound and outbound gossiped DKGMessages
- [ ] [TASK] Handle threshold changes 
- [ ] [TASK] Compute signature share of message (proposal)
- [ ] [TASK] Sign unsigned Proposals
- [ ] [TASK] Manage proposer voting 

### Testing
- [ ] [TASK] Adding and removing collators with varying frequency 
- [ ] [TASK] Updating thresholds  
- [ ] [TASK] DKG specific RPC calls work as intended 
- [ ] [TASK] Involve multiple bad acting nodes

### Infrastructure requirements 
- [ ] Relaychain validator nodes    
- [ ] DKG collator nodes  
- [ ] Observability pipeline (e.g. prometheus, grafana, loki) - main goal here to be able to have visibility into the TestNet to identify bugs/issues or areas of improvement

**Comment by dutterbutter** [comment]
Closing in favour of #230
