### ISSUE TITLE
[CHECKLIST] [WIP] Road to Rococo phase-2 | DKG parachain 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#230]
# Overview

The goal of this checklist is to outline all requirements to have the DKG running as a parachain on the Rococo testnet. This is an essential step to ensure the DKG is launch-ready before securing a slot on Kusama. 

The registered DKG parachain running on Rococo should be a fully-functioning implementation of the intended DKG.  

### Feature-complete list
- [ ] [TASK] Initiate and complete key-gen protocol 
           - [ ] Node are generating secret parameter 
           - [ ] Nodes are able to gossip VSS of each parties secret parameter
           - [ ] Each party can generate their private signing key share 
- [ ] [TASK] Proceed through rounds with adequate signers   
- [ ] [TASK] Handle inbound and outbound gossiped DKGMessages
- [ ] [TASK] Handle threshold changes 
- [ ] [TASK] Compute signature share of message (proposal)
- [ ] [TASK] Sign unsigned Proposals
- [ ] [TASK] Manage proposer voting

### Testing
- [ ] [TASK] Adding and removing collators with varying frequency 
- [ ] [TASK] Updating thresholds  
- [ ] # Issue number 

### Other related tasks
- [ ] [TASK] Secure a parachain slot via crowdloan operation with Rococo testnet token
- [ ] # Issue number  
- [ ] # Issue number
