### ISSUE TITLE
[SPEC] DKG Authority Reputation System

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#269]
# Overview 

## Tasks

Investigate and spec out improving the existing authority reputation system. 

- [ ] Spec implementation of shuffling keygen authorities / signing authorities on misbehaviour reports
- [ ] Explore a short-term / long-term reputation system
- [ ] Short-term for adapting to timeouts/errors immediately in keygen signing
- [ ] Long-term for adapting to the best authorities participating in the protocol. (they should be selected as often as possible)
- [ ] Investigate suspending or chilling authority from keygen process for x amount of sessions

# Questions / Tasks

- If we hear of a keygen misbehaviour, how to ensure that we keep trying to execute keygen afterwards?
- When should we reduce the threshold on-chain?
- Would a state diagram be helpful here?
