### ISSUE TITLE
[TASK] Tracking network test cases for launch readiness

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/dkg-substrate#308]
**Task summary**

The purpose of this checklist is outline a list of test cases that we must check, observe, and document before launch. These test cases involve running a live testnet network and initiating a variety of different operations to see how the chain and dkg respond. 

- [x] Add a validator(s) to a running chain and observe / document behavior
	- Start the normal 3 node DKG (_1-out-of-3_ threshold).
	- Add a 4th node to the validator set.
	- Ensure the authorities count is now 4 nodes and that the DKG runs and refreshes properly.
	- Remove the 4th node from the validator set.
	- Ensure the authorities count is now 3 nodes and that the DKG runs and refreshes properly.
- [x] Remove validator(s) from a running chain and observe / document behavior 
- [x] Increase keygen threshold after some time using the extrinsic `setKeygenThreshold` by x number of validators added to the network - observe and document behavior 
- [x] Decrease keygen threshold after some time using the extrinsic `setKeygenThreshold` by x number of validators removed from the network - observe and document behaviour 
- [x] Repeat the above tests on the live testnet network:
	- Start the normal 3 node DKG (_1-out-of-3_ threshold).
	- Add a 4th node to the validator set.
	- Ensure the authorities count is now 4 nodes and that the DKG runs and refreshes properly.
	- Increase the signature threshold by 2. It should be now a (_3-out-of-4 threshold)
	- Remove the 4th node from the validator set.
	- Ensure we check the authority # with respect to the signature threshold and if `threshold >= authority_count` set the `threshold = authority_count - 1`.
		- The threshold should automatically return back to _2-out-of-3_ after removing.
	- Ensure the authorities count is now 3 nodes and that the DKG runs and refreshes properly.

**Comment by dutterbutter** [comment]
@1xstj @drewstone can we consider this closed?

**Comment by 1xstj** [comment]
All test cases passing, more details [here](https://www.notion.so/hicommonwealth/Tracking-network-test-cases-for-launch-readiness-77e3d8fd270f4f18be1d17592eaf003f)
