### ISSUE TITLE
[TASK] Keep track of currently being signed proposals to avoid re-signing

### ISSUE THREAD

**Issue by shekohex** [webb-tools/dkg-substrate#386]
**Task summary**
Currently, on every new block notification to the DKG worker, we call this method here [`process_block_notification`](https://github.com/webb-tools/dkg-substrate/blob/4822cdac1ff803cc66d52f6fdd06b76768c77296/dkg-gadget/src/worker.rs#L734) and later on we will then call [`submit_unsigned_proposals `](https://github.com/webb-tools/dkg-substrate/blob/4822cdac1ff803cc66d52f6fdd06b76768c77296/dkg-gadget/src/worker.rs#L1098) which later fetches the `UnsignedProposals` from on chain storage and submit them to be signed by the DKG worker.

The issue resides is that we do not keep track of these tasks and what they are signing (internally in the worker) which result in doing more work than needed. The Unsigned Proposal is ever removed from on-chain storage once it gets signed by the DKG worker and submitted on chain, then it gets moved from the Unsigned Proposal Queue to the Signed Proposals storage. The Off-chain worker will keep trying to process/sign the unsigned proposal over and over and starting new signing rounds until it is finally signed. 

**Specification reference**

- [ ] Keep track of the currently being signed proposal using a `HashSet` of the proposals hash (_option 1_).
- [ ] Keep track of the currently being signed proposals using a Queue, where we first push the unsigned proposals to the queue, and once signed we remove it from the queue (_option 2_).
- [ ] Before processing the same proposal again, check if it is currently being signed or not.
- [ ] When a signing round finish, remove the proposal hash from the queue/hashset.

**Other information and links**
