### ISSUE TITLE
[CHECKLIST] DKG Stress Test

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#513]
# Overview
The goal of this checklist is to stress test various aspects of the DKG on our testnet

### Threshold
- [X] DKG rotates 100 sessions with t=2, n=3
- [X] DKG rotates 100 sessions with t=3, n=5
- [X] DKG rotates 100 sessions with t=4, n=10
- [x] DKG rotates 100 sessions with t=6, n=12
- [X] DKG handles increase and decrease of t/n

### Metrics
- [X] Track unsigned proposals in a session (https://github.com/webb-tools/dkg-substrate/pull/488)
- [X] Track proposals signed in a session (https://github.com/webb-tools/dkg-substrate/pull/488)
- [X] Log inbound/outbound messages for DKG (https://github.com/webb-tools/dkg-substrate/pull/488)
- [x] Compare and document above metrics for every change in threshold

### Functionality
- [X] Active DKG signs proposals when stable 
- [ ] DKG signs proposals when stalled (Important)
