### ISSUE TITLE
[CHECKLIST] DKG Signing Manager v2

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#529]
## Product Description

- The Signing manager currently suffers from a lot of redundancy. Every signing set signs the same message, and every signed message attempts to get submitted by each authority. We need to build a more parallelizable and fault-tolerant mechanism that helps us reduce our network throughput, while also increasing our signing throughput respectively.

## Features List

- To be more parallelizable
- To reduce network throughput per unsigned proposal
- To increase signing throughput per batch of unsigned proposals

## Task Checklist

- [x]  Leverage existing specs, and design + propose new Signing Manager mechanisms.
- [x]  Schedule time with key parties (Drew, Akilesh, Shady, Stanly, Thomas) and discuss.
- [ ] [TASK] Create rough diagrams that can be converted into well-designed visual descriptions of the Signing Manager.
- [ ] [TASK] Implement the new Signing Manager traits
- [ ] [TASK] Preprocess offline stages in bulk with an adaptable mechanism.
- [ ] [TASK] Parallelize signing operations for `1..n` sized batches of unsigned proposals.
- [ ] [TASK] Implement resiliency logic in the event of failure at any step.
- [ ] [TASK]Test using DKG harness and benchmark against previous signing mechanism.

## Resources
[https://github.com/webb-tools/dkg-substrate/issues/393](https://github.com/webb-tools/dkg-substrate/issues/393)
[https://github.com/webb-tools/dkg-substrate/pull/403](https://github.com/webb-tools/dkg-substrate/pull/403)
