### ISSUE TITLE
[CHECKLIST] Substrate Builder Program - Milestone Review 2

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#573]
# Overview
Checklist to address SBP feedback here https://github.com/webb-tools/dkg-substrate/pull/569

## Checklist
- [x] https://github.com/webb-tools/webb-docs/issues/93
- [x] https://github.com/webb-tools/dkg-substrate/issues/570
- [ ] https://github.com/webb-tools/dkg-substrate/issues/571
- [x] https://github.com/webb-tools/dkg-substrate/issues/572
