### ISSUE TITLE
[CHECKLIST] Improve Documentation

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/dkg-substrate#596]
# Overview
The goal is to improve the state of documentation and README in general

## Checklist
For every crate/pallet we should
- [ ] Add a README with an overview on what the crate/pallet does and how to use/test it
- [ ] Improve rust docs where possible

### Crates
- [ ] Dkg-metadata
- [ ] dkg-proposals
- [ ] dkg-proposal-handler
- [ ] dkg-gadget
- [ ] dkg-orchestrator
- [ ] dkg-logging
- [ ] dkg-mock-blockchain
- [ ] dkg-test-suite

**Comment by drewstone** [comment]
Possible useful tool: https://docs.rs/cargo-readme/latest/cargo_readme/
