### ISSUE TITLE
[CHECKLIST] E2E SignatureBridge Integration

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#92]
# Overview
The goal of this checklist is to document tasks needed to complete to take us to an E2E SignatureBridge integration.

### Functionality
- [x] #41 
- [x] #79 
- [x] #96
- [x] #111
- [ ] [[SPEC] Validation for Substrate signed call proposals on the pallet-signature-bridge.](https://github.com/webb-tools/protocol-substrate/issues/105)
- [x] #114

### Testing
- [x] #80 
- [x] #97
- [x] #98
- [x] #99
- [x] #100
- [x] #101
- [x] #102
- [x] #103
- [x] #104
- [x] [[TASK] Write test utilities for creating Substrate proposal structure.](https://github.com/webb-tools/protocol-substrate/issues/104)
- [x] #108

### Process
- [x] #90 
- [x] #91 
- [x] #105

## Relayer
- [x] https://github.com/webb-tools/relayer/issues/92
- [x] https://github.com/webb-tools/relayer/issues/93
- [x] https://github.com/webb-tools/relayer/issues/94
- [x] https://github.com/webb-tools/relayer/issues/137

**Comment by dutterbutter** [comment]
Great work @shekohex 👏
